SHOW USER;
DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    MFILE NVARCHAR2(50),
    MID NVARCHAR2(20) CONSTRAINT PK_MEMBER PRIMARY KEY,
    MPASSWORD NVARCHAR2(20),
    MNAME NVARCHAR2(10),
    MGENDER NVARCHAR2(5),
    MPHONE NVARCHAR2(20),
    MBIRTH DATE,
    MEMAIL NVARCHAR2(20),
    MADDRESS1 NVARCHAR2(30),
    MADDRESS2 NVARCHAR2(30),
    MADDRESS3 NVARCHAR2(30),
    MADDRESS4 NVARCHAR2(30));
    
SELECT * FROM MEMBER;
    
    
----------------------------------------------------------    
    
DROP TABLE BOARD;
CREATE TABLE BOARD(
    BKATEGORIE NVARCHAR2(10),
    BNUMBER NUMBER CONSTRAINT PK_BOARD PRIMARY KEY,
    BTITLE NVARCHAR2(20),
    BWRITER NVARCHAR2(20),
    BCONTENTS NVARCHAR2(500),
    BFILE NVARCHAR2(100),
    BDATE DATE,
    BHITS NUMBER,
    BTAG1 NVARCHAR2(10),
    BTAG2 NVARCHAR2(10),
    BTAG3 NVARCHAR2(10));
    
SELECT * FROM BOARD;

CREATE SEQUENCE BOARD_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

SELECT * FROM BOARD ORDER BY BHITS DESC;
drop view boardlist;
CREATE VIEW BOARDLIST AS SELECT B.*, ROW_NUMBER() OVER(ORDER BY BHITS DESC) AS RN FROM BOARD B;
drop view memberlist;
CREATE VIEW MEMBERLIST AS SELECT M.*, ROW_NUMBER() OVER(ORDER BY MID) AS RN FROM MEMBER M;